### ISSUE TITLE
config variables in site.conf and merge with ffac version

### ISSUE THREAD

**Issue by rubo77** [Freifunk-Nord/gluon-ssid-changer#5]
Add conf variables definable in site.conf:

* minutes - after haw many minutes it may be set to offline
* first - the first run, where it will be set to offline
* tq - merge from ffac, if set, then the tq to the next gateway is taken into account
* disable

All of these variables should be stored via uci as well

closes #3

**Comment by rubo77** [comment]
suggestion for the config section in site.conf:

```
ssid_changer = {
  switch_timeframe = 1,   -- only once every timeframe (in minutes) the SSID will change to OFFLINE 
                          -- set to 1440 to change once a day
                          -- set to 1 minute to change every time the router gets offline
  first = 5,              -- the first few minutes directly after reboot within which an Offline-SSID always may be activated
  prefix = 'FF_OFFLINE_', -- use something short to leave space for the nodename (no '~' allowed!)
  suffix = 'nodename',    -- generate the SSID with either 'nodename', 'mac' or to use only the prefix: 'none'
  
  tq_limit_enabled = 0,   -- if false, the offline SSID will only be set if there is no gateway reacheable
                          -- upper and lower limit to turn the offline_ssid on and off
                          -- in-between these two values the SSID will never be changed to prevent it from toggeling every minute.
                          -- TODO: enabled=1 still has to be implemented
  tq_limit_max = '55',    -- upper limit, above that the online SSID will be used
  tq_limit_min = '45'     -- lower limit, below that the offline SSID will be used
}
```

**Comment by rubo77** [comment]
This works already in the branch [''configurable"](https://github.com/Freifunk-Nord/gluon-ssid-changer/tree/configurable#commandline-options).

### successful tests:

- [x] flash without ssid-changer installed with default settings
- [x] changed settings are kept after sysupgrade
- [x] flash without ssid-changer installed with other settings than default in site.conf

### todo

- [ ] tq einbauen

**Comment by rubo77** [comment]
strange, the new config doesn't land in `/lib/gluon/site.json` on the router, so the upgrade script cannot read it.

I Committed the new [ssid-changer branch in our site.conf](https://github.com/Freifunk-Nord/nord-site/tree/ssid-changer)

**Comment by rubo77** [comment]
now the variables from site.conf are taken successfully
